---
- hosts: all
  tasks:
    
  - name: Get last version of wave application 
    local_action: shell curl -k --silent {{remoute_repocitory_of_applications_files}} | sed 's/.*href\="//p' | sed 's/".*//p' | grep 'gz.enc' | sort | tail -1
    register: app_version
    tags:
       - check
       - update
       - local

  - name: Print
    debug: var=app_version.stdout
    tags:
       - check
       - update
       - local

  - name: download wave application
    local_action: shell wget --no-check-certificate -P ~/  {{remoute_repocitory_of_applications_files}}{{ app_version.stdout }}
    tags:
       - local
       - update

  - name: Copy to remote host
    copy:
      src: ~/{{ app_version.stdout }}
      dest: /tmp/
    tags:
       - update

  - name: Copy to directory
    shell: sudo /usr/bin/install -g www-data -m 440 /tmp/{{ app_version.stdout }} /var/www/
    tags:
       - update
      
