---
- hosts: all
  tasks:

    - name: grep dpkg
      shell: sudo -i dpkg -l|grep zabbix

    - name: grep ps
      shell: sudo -i ps -A|grep zabbix

    - name: service status
      shell: sudo -i service zabbix-agent status

    - name: grep config files
      shell: sudo -i grep oets /etc/zabbix/zabbix_agentd.d/*.conf
