---
- hosts: all
  sudo: yes
  tasks:

  - name: Set authorized key took from file
    authorized_key:
      user: {{user_name}}
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
