---
- hosts: all
  tasks:

    - name: Make backup directory
      shell: sudo -i mkdir /root/{{date}}

    - name: Make backup copy of zabbix config file
      shell: sudo -i cp /etc/zabbix/zabbix_agentd.d/* /root/{{date}}

    - name: get distrib file
      shell: wget http://repo.zabbix.com/zabbix/3.2/debian/pool/main/z/zabbix/{{zabbix-agent}}

    - name: install new version of zabbix agent
      shell: sudo dpkg -i --force-confold {{zabbix-agent}}

    - name: Restarting service new variant
      shell: sudo -i service zabbix-agentd restart
